from wnmanager import wm

wm.open()

wm.add_synset('n',['on line bank'], [('@',wm.wndata.lemmas['n']['bank'].offsets[1],'n','0000')], 'a bank that offers its services on the internet', from_history = True)
wm.add_synset('n',['lehman brothers'], [('@',wm.wndata.lemmas['n']['finance_company'].offsets[0],'n','0000')], 'banca rappresentante il male assoluto', from_history = True)
wm.add_synset('n',['accounting adjustment'], [('#p',wm.wndata.lemmas['n']['accounting_system'].offsets[0],'n','0000')], 'corrections of the accounting system', from_history = True)
wm.add_synset('n',['unilateral modification'], [('@',wm.wndata.lemmas['n']['modification'].offsets[0],'n','0000')], 'the act of making something different without the permission of all party involved', from_history = True)
wm.add_synset('n',['ex-customer'],[('@',wm.wndata.lemmas['n']['customer'].offsets[0],'n','000')],'an old customer who has terminated the relationship with the business', from_history = True)
wm.add_synset('n',['failure to reply'],[('!',wm.wndata.lemmas['n']['reply'].offsets[0],'n','0000')],"inexistent reply to a call or some other actions", from_history = True)
wm.add_synset('n',['event context'],[('@',wm.wndata.lemmas['n']['context'].offsets[1],'n','0000')],"a context in which a bank loss event occurred", from_history = True)
wm.add_synset('n',['bank software'],[('@',wm.wndata.lemmas['n']['software_system'].offsets[0],'n','0000')],"a software that banks use to operate their business", from_history = True)
wm.add_synset('n',['telephone top-up'],[('@',wm.wndata.lemmas['n']['top-up'].offsets[0],'n','0000'),('@',wm.wndata.lemmas['n']['refilling'].offsets[0],'n','0000')],"a telephone sim card refilling of money", from_history = True)
wm.add_synset('n',['legal subject'],[('@',wm.wndata.lemmas['n']['individual'].offsets[0],'n','0000')],"an individual in its legal entity", from_history = True)
wm.add_synset('n',['signature loan'],[('@',wm.wndata.lemmas['n']['loan'].offsets[0],'n','0000')],"an unsecured personal loans offered by banks and other financial institutions. Instead of relying on the applicant’s assets as collateral, a signature loan relies on a borrower’s signature as a promise to pay. ", from_history = True)
wm.add_synset('n',['legal expense'],[('@',wm.wndata.lemmas['n']['expense'].offsets[0],'n','0000')],"any expense, fee or cost incurred by any person and its counsel in defending from a legal claim", from_history = True)
wm.add_synset('n', ['customer complaint'], [ ('@', wm.wndata.lemmas['n']['claim'].offsets[0], 'n', '0000')], 'an expression of unhappiness towards a service made from customers', from_history = True )
wm.add_synset('n', ['data flow'], [ ('@', wm.wndata.lemmas['n']['event_context'].offsets[0], 'n', '0000')], 'a flow of data regarding a bank operation coming from a provider (ie ICCREA)', from_history = True )
wm.add_synset('n', ['money loss'], [ ('@', wm.wndata.lemmas['n']['loss'].offsets[3], 'n', '0000')], 'the disadvantage that results from losing money', from_history = True )
wm.add_synset('n', ['ultra legal interest rate'], [ ('@', wm.wndata.lemmas['n']['interest_rate'].offsets[0], 'n', '0000')], 'an interest rate that exceeds the maximum legal percentage' , from_history = True)

wm.add_word('prelevamenti', 'n', wm.wndata.lemmas['n']['withdrawal'].offsets[1], lang='ita', from_history = True)
wm.add_word('prelevamento', 'n', wm.wndata.lemmas['n']['withdrawal'].offsets[1], lang='ita', from_history = True)
wm.add_word('disservizio', 'n', wm.wndata.lemmas['n']['disservice'].offsets[0], lang='ita', from_history = True)
wm.add_word('estratto', 'n', wm.wndata.lemmas['n']['account_statement'].offsets[0], lang='ita', from_history = True)
wm.add_word('trimestrale', 'n', wm.wndata.lemmas['n']['quarterly'].offsets[0], lang='ita', from_history = True)
wm.add_word('sistemi informatici', 'n', wm.wndata.lemmas['n']['computer_system'].offsets[0], lang='ita', from_history = True)
wm.add_word('c/c', 'n', wm.wndata.lemmas['n']['bank_account'].offsets[0], lang='ita', from_history = True)
wm.add_word('banca on line', 'n', wm.wndata.lemmas['n']['on_line_bank'].offsets[0], lang='ita', from_history = True)
wm.add_word('lehman brothers', 'n', wm.wndata.lemmas['n']['on_line_bank'].offsets[0], lang='ita', from_history = True)
wm.add_word('sistemazioni contabili', 'n', wm.wndata.lemmas['n']['accounting_adjustment'].offsets[0], lang='ita', from_history = True)
wm.add_word('sistemazione contabile', 'n', wm.wndata.lemmas['n']['accounting_adjustment'].offsets[0], lang='ita', from_history = True)
wm.add_word('conti transitori', 'n', wm.wndata.lemmas['n']['suspense_account'].offsets[0], lang='ita', from_history = True)
wm.add_word('conto transitorio', 'n', wm.wndata.lemmas['n']['suspense_account'].offsets[0], lang='ita', from_history = True)
wm.add_word('modifica unilaterale', 'n', wm.wndata.lemmas['n']['unilateral_modification'].offsets[0], lang='ita', from_history = True)
wm.add_word('carta','n',wm.wndata.lemmas['n']['credit_card'].offsets[0],lang='ita', from_history = True)
wm.add_word('gestito','a',wm.wndata.lemmas['a']['supervised'].offsets[0],lang='ita', from_history = True)
wm.add_word('gestita','a',wm.wndata.lemmas['a']['supervised'].offsets[0],lang='ita', from_history = True)
wm.add_word('contattato','v',wm.wndata.lemmas['v']['contact'].offsets[0],lang='ita', from_history = True)
wm.add_word('ex cliente','n',wm.wndata.lemmas['n']['ex-customer'].offsets[0],lang='ita', from_history = True)
wm.add_word('ex clienti','n',wm.wndata.lemmas['n']['ex-customer'].offsets[0],lang='ita', from_history = True)
wm.add_word('avere possesso','v',wm.wndata.lemmas['v']['own'].offsets[0],lang='ita', from_history = True)
wm.add_word('avere in possesso','v',wm.wndata.lemmas['v']['own'].offsets[0],lang='ita', from_history = True)
wm.add_word('consegnata','v',wm.wndata.lemmas['v']['deliver'].offsets[1],lang='ita', from_history = True)
wm.add_word('rapporti','n',wm.wndata.lemmas['n']['relationship'].offsets[2],lang='ita', from_history = True)
wm.add_word('blocco','v',wm.wndata.lemmas['v']['freeze'].offsets[4],lang='ita', from_history = True)
wm.add_word('ulteriori','n',wm.wndata.lemmas['n']['extra'].offsets[2],lang='ita', from_history = True)
wm.add_word('addebiti','n',wm.wndata.lemmas['n']['debit_entry'].offsets[0],lang='ita', from_history = True)
wm.add_word('recuperabile','a',wm.wndata.lemmas['a']['retrievable'].offsets[0],lang='ita', from_history = True)
wm.add_word('recuperabili','a',wm.wndata.lemmas['a']['retrievable'].offsets[0],lang='ita', from_history = True)
wm.add_word('fraudolento','n',wm.wndata.lemmas['n']['dupery'].offsets[0],lang='ita', from_history = True)
wm.add_word('carta bancomat','n',wm.wndata.lemmas['n']['credit_card'].offsets[0],lang='ita', from_history = True)
wm.add_word('smarrita','a',wm.wndata.lemmas['a']['lost'].offsets[0],lang='ita', from_history = True)
wm.add_word('smarrito','a',wm.wndata.lemmas['a']['lost'].offsets[0],lang='ita', from_history = True)
wm.add_word('lamenta','v',wm.wndata.lemmas['v']['complain'].offsets[0],lang='ita', from_history = True)
wm.add_word('risposte','n',wm.wndata.lemmas['n']['reply'].offsets[0],lang='ita', from_history = True)
wm.add_word('mancata risposta','n',wm.wndata.lemmas['n']['failure_to_reply'].offsets[0],lang='ita', from_history = True)
wm.add_word('mancate risposte','n',wm.wndata.lemmas['n']['failure_to_reply'].offsets[0],lang='ita', from_history = True)
wm.add_word('spese legali','n',wm.wndata.lemmas['n']['legal_expense'].offsets[0],lang='ita', from_history = True)
wm.add_word('ambiente impattato','n',wm.wndata.lemmas['n']['event_context'].offsets[0],lang='ita', from_history = True)
wm.add_word('ambiente impatto','n',wm.wndata.lemmas['n']['event_context'].offsets[0],lang='ita', from_history = True)
wm.add_word("ambiente d impatto",'n',wm.wndata.lemmas['n']['event_context'].offsets[0],lang='ita', from_history = True)
wm.add_word('gestionale auriga','n',wm.wndata.lemmas['n']['bank_software'].offsets[0],lang='ita', from_history = True)
wm.add_word('auriga','n',wm.wndata.lemmas['n']['bank_software'].offsets[0],lang='ita', from_history = True)
wm.add_word('carta di debito','n',wm.wndata.lemmas['n']['credit_card'].offsets[0],lang='ita', from_history = True)
wm.add_word('carte di debito','n',wm.wndata.lemmas['n']['credit_card'].offsets[0],lang='ita', from_history = True)
wm.add_word('carte di credito','n',wm.wndata.lemmas['n']['credit_card'].offsets[0],lang='ita', from_history = True)
wm.add_word('reclama','n',wm.wndata.lemmas['n']['customer_complaint'].offsets[0],lang='ita', from_history = True)
wm.add_word('reclamo', 'n', wm.wndata.lemmas['n']['customer_complaint'].offsets[0], lang='ita', from_history = True)
wm.add_word('addebito','n',wm.wndata.lemmas['n']['debit_entry'].offsets[0],lang='ita', from_history = True)
wm.add_word('carabinieri','n',wm.wndata.lemmas['n']['police'].offsets[0],lang='ita', from_history = True)
wm.add_word('guardia di finanza','n',wm.wndata.lemmas['n']['police'].offsets[0],lang='ita', from_history = True)
wm.add_word('ricarica telefonica','n',wm.wndata.lemmas['n']['telephone_top-up'].offsets[0],lang='ita', from_history = True)
wm.add_word('atm','n',wm.wndata.lemmas['n']['atm'].offsets[2],lang='ita', from_history = True)
wm.add_word('sportello bancomat','n',wm.wndata.lemmas['n']['atm'].offsets[2],lang='ita', from_history = True)
wm.add_word('riutilizzate','v',wm.wndata.lemmas['v']['reuse'].offsets[0],lang='ita', from_history = True)
wm.add_word('riutilizzati','v',wm.wndata.lemmas['v']['reuse'].offsets[0],lang='ita', from_history = True)
wm.add_word('coinvolte','a',wm.wndata.lemmas['a']['involved'].offsets[0],lang='ita', from_history = True)
wm.add_word('coinvolti','a',wm.wndata.lemmas['a']['involved'].offsets[0],lang='ita', from_history = True)
wm.add_word('direttamente coinvolte','a',wm.wndata.lemmas['a']['involved'].offsets[0],lang='ita', from_history = True)
wm.add_word('direttamente coinvolti','a',wm.wndata.lemmas['a']['involved'].offsets[0],lang='ita', from_history = True)
wm.add_word('direttamente coinvolto','a',wm.wndata.lemmas['a']['involved'].offsets[0],lang='ita', from_history = True)
wm.add_word('direttamente coinvolta','a',wm.wndata.lemmas['a']['involved'].offsets[0],lang='ita', from_history = True)
wm.add_word('sostituite','v',wm.wndata.lemmas['v']['replace'].offsets[0],lang='ita', from_history = True)
wm.add_word('sostituita','v',wm.wndata.lemmas['v']['replace'].offsets[0],lang='ita', from_history = True)
wm.add_word('sostituiti','v',wm.wndata.lemmas['v']['replace'].offsets[0],lang='ita', from_history = True)
wm.add_word('sostituito','v',wm.wndata.lemmas['v']['replace'].offsets[0],lang='ita', from_history = True)
wm.add_word('problematica','n',wm.wndata.lemmas['n']['trouble'].offsets[0],lang='ita', from_history = True)
wm.add_word('carte','n',wm.wndata.lemmas['n']['credit_card'].offsets[0],lang='ita', from_history = True)
wm.add_word('bloccano','v',wm.wndata.lemmas['v']['freeze'].offsets[4],lang='ita', from_history = True)
wm.add_word('bloccate','v',wm.wndata.lemmas['v']['freeze'].offsets[4],lang='ita', from_history = True)
wm.add_word('rischio','n',wm.wndata.lemmas['n']['event_context'].offsets[0],lang='ita', from_history = True)
wm.add_word('rischi','n',wm.wndata.lemmas['n']['event_context'].offsets[0],lang='ita', from_history = True)
wm.add_word('beni materiali','n',wm.wndata.lemmas['n']['property'].offsets[0],lang='ita', from_history = True)
wm.add_word('beni e materiali','n',wm.wndata.lemmas['n']['property'].offsets[0],lang='ita', from_history = True)
wm.add_word('soggetti esterni','n',wm.wndata.lemmas['n']['legal_subject'].offsets[0],lang='ita', from_history = True)
wm.add_word('soggetti terzi','n',wm.wndata.lemmas['n']['legal_subject'].offsets[0],lang='ita', from_history = True)
wm.add_word('commissioni','n',wm.wndata.lemmas['n']['commission'].offsets[1],lang='ita', from_history = True)
wm.add_word('causa per','n',wm.wndata.lemmas['n']['event_context'].offsets[0],lang='ita', from_history = True)
wm.add_word('organico','n',wm.wndata.lemmas['n']['staff'].offsets[0],lang='ita', from_history = True)
wm.add_word('chiede','v',wm.wndata.lemmas['v']['request'].offsets[0],lang='ita', from_history = True)
wm.add_word('chiesto','v',wm.wndata.lemmas['v']['request'].offsets[0],lang='ita', from_history = True)
wm.add_word('richiede','v',wm.wndata.lemmas['v']['request'].offsets[0],lang='ita', from_history = True)
wm.add_word('emette','v',wm.wndata.lemmas['v']['issue'].offsets[2],lang='ita', from_history = True)
wm.add_word('fideiussione','n',wm.wndata.lemmas['n']['signature_loan'].offsets[0],lang='ita', from_history = True)
wm.add_word('fideiussioni','n',wm.wndata.lemmas['n']['signature_loan'].offsets[0],lang='ita', from_history = True)
wm.add_word('credito di firma','n',wm.wndata.lemmas['n']['signature_loan'].offsets[0],lang='ita', from_history = True)
wm.add_word('concede','v',wm.wndata.lemmas['v']['grant'].offsets[4],lang='ita', from_history = True)
wm.add_word('concesso','v',wm.wndata.lemmas['v']['grant'].offsets[4],lang='ita', from_history = True)
wm.add_word('concessa','v',wm.wndata.lemmas['v']['grant'].offsets[4],lang='ita', from_history = True)
wm.add_word('addebitate','n',wm.wndata.lemmas['n']['debit_entry'].offsets[0],lang='ita', from_history = True)
wm.add_word('respinto','v',wm.wndata.lemmas['v']['spurn'].offsets[0],lang='ita', from_history = True)
wm.add_word('respinta','v',wm.wndata.lemmas['v']['spurn'].offsets[0],lang='ita', from_history = True)
wm.add_word('respinti','v',wm.wndata.lemmas['v']['spurn'].offsets[0],lang='ita', from_history = True)
wm.add_word('respinte','v',wm.wndata.lemmas['v']['spurn'].offsets[0],lang='ita', from_history = True)
wm.add_word('violazione', 'n', wm.wndata.lemmas['n']['wrongdoing'].offsets[1], lang='ita', from_history = True)
wm.add_word('perdita monetaria', 'n', wm.wndata.lemmas['n']['money_loss'].offsets[0], lang='ita', from_history = True)
wm.add_word('perdita', 'n', wm.wndata.lemmas['n']['money_loss'].offsets[0], lang='ita', from_history = True)
wm.add_word('clienti', 'n', wm.wndata.lemmas['n']['customer'].offsets[0], lang='ita', from_history = True)
wm.add_word('danni', 'n', wm.wndata.lemmas['n']['wrong'].offsets[1], lang='ita', from_history = True)
wm.add_word('rapine', 'n', wm.wndata.lemmas['n']['robbery'].offsets[0], lang='ita', from_history = True)
wm.add_word('appropriazioni indebite', 'n', wm.wndata.lemmas['n']['embezzlement'].offsets[0], lang='ita', from_history = True)
wm.add_word('flusso', 'n', wm.wndata.lemmas['n']['data_flow'].offsets[0], lang='ita', from_history = True)
wm.add_word('problemi tecnici', 'n', wm.wndata.lemmas['n']['failure'].offsets[6], lang='ita', from_history = True)
wm.add_word('cc', 'n', wm.wndata.lemmas['n']['bank_account'].offsets[0], lang='ita', from_history = True)
wm.add_word('tasso', 'n', wm.wndata.lemmas['n']['interest_rate'].offsets[0], lang='ita', from_history = True)
wm.add_word('tasso ultra legale', 'n', wm.wndata.lemmas['n']['ultra_legal_interest_rate'].offsets[0], lang='ita', from_history = True)
wm.add_word('interesse ultra legale', 'n', wm.wndata.lemmas['n']['ultra_legal_interest_rate'].offsets[0], lang='ita', from_history = True)
wm.add_word('interessi ultra legali', 'n', wm.wndata.lemmas['n']['ultra_legal_interest_rate'].offsets[0], lang='ita', from_history = True)
wm.add_word('tassi ultra legali', 'n', wm.wndata.lemmas['n']['ultra_legal_interest_rate'].offsets[0], lang='ita', from_history = True)
wm.add_word('applicato', 'n', wm.wndata.lemmas['n']['application'].offsets[0], lang='ita', from_history = True)

wm.add_sense_disambiguation('l', -1, from_history = True)
wm.add_sense_disambiguation('l', 0, from_history = True)
wm.add_sense_disambiguation('cliente', 2, from_history = True)
wm.add_sense_disambiguation('esempio', 0, from_history = True)
wm.add_sense_disambiguation('flusso', 4, from_history = True)
wm.add_sense_disambiguation('flusso', 5, from_history = True)
wm.add_sense_disambiguation('applicazione', 3, from_history = True)
wm.add_sense_disambiguation('tasso', 5, from_history = True)
wm.add_sense_disambiguation('cc', 2, from_history = True)
wm.add_sense_disambiguation('tasso', 7, from_history = True)

wm.commit_changes()
